spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2example
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
      # create : 어플리케이션 로딩 시점에 테이블들을 모두 drop 하고 테이블을 다시 생성
      # create-drop : 어플리케이션 로딩 시점에 테이블들을 모두 drop하고 테이블을 다시 생성, 종료할때 모두 drop
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
#        use_sql_comments: true

logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace